name: pokedex
description: App to find pokemons

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5
  flutter_svg_provider: ^1.0.3
  auto_size_text: ^3.0.0
  syncfusion_flutter_sliders: ^20.2.48
  syncfusion_flutter_core: ^20.2.48
  intl: ^0.17.0
  numerus: ^2.0.0
  flutter_bloc: ^8.1.1
  uno: ^1.0.1+3
  provider: ^6.0.3
  graphql_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/generations/generation1/
    - assets/generations/generation2/
    - assets/generations/generation3/
    - assets/generations/generation4/
    - assets/generations/generation5/
    - assets/generations/generation6/
    - assets/generations/generation7/
    - assets/generations/generation8/
    - assets/types/
    - assets/weights/
    - assets/heights/
    - assets/patterns/

  fonts:
    - family: 'SF Pro Display'
      fonts:
        - asset: 'assets/fonts/sf-pro-display-bold.ttf'
        - asset: 'assets/fonts/sf-pro-display-medium.ttf'
        - asset: 'assets/fonts/sf-pro-display-regular.ttf'
