name: pokedex
description: App to find pokemons

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  flutter_svg_provider: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/generations/generation1/
    - assets/types/
    - assets/patterns/

  fonts:
    - family: 'SF Pro Display'
      fonts:
        - asset: 'assets/fonts/sf-pro-display-bold.ttf'
        - asset: 'assets/fonts/sf-pro-display-medium.ttf'
        - asset: 'assets/fonts/sf-pro-display-regular.ttf'
