name: instagram_clone
description: A Instagram Clone

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  #firebase
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  #service locator
  get_it: ^7.2.0

  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  intl: ^0.17.0
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  #show toast
  fluttertoast: ^8.1.2
  modal_bottom_sheet: ^2.1.2

  cupertino_icons: ^1.0.2
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/instagram.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/instagram.png"

flutter:

  uses-material-design: true

  assets:
    - assets/.
