name: frivia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  get_it: ^7.2.0
  dio: ^4.0.6

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  fonts:
    - family: Architects Daughter
      fonts:
        - asset: assets/fonts/ArchitectsDaughter-Regular.ttf
