name: pokedex
description: A pokedex

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Bold.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Medium.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Light.ttf
