// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9wC0n7mpXjRV76vJmA1a1O0im669ihWU',
    appId: '1:477898817448:web:50cba8c0c7faf67bbfa79d',
    messagingSenderId: '477898817448',
    projectId: 'queue-management-ac2e9',
    authDomain: 'queue-management-ac2e9.firebaseapp.com',
    storageBucket: 'queue-management-ac2e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfenY1CbQO9MkuMRNGNOnaoysVVCtbv94',
    appId: '1:477898817448:android:0344f249f4e0cc5cbfa79d',
    messagingSenderId: '477898817448',
    projectId: 'queue-management-ac2e9',
    storageBucket: 'queue-management-ac2e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwjzY3evKwHTPBfivA0Rk3WfjzA3kRaw',
    appId: '1:477898817448:ios:12d569831229635abfa79d',
    messagingSenderId: '477898817448',
    projectId: 'queue-management-ac2e9',
    storageBucket: 'queue-management-ac2e9.appspot.com',
    iosClientId: '477898817448-rvognkkp2jiq8mosajq53umpp7h7trb7.apps.googleusercontent.com',
    iosBundleId: 'com.xandecoelho5.queueManagement',
  );
}
