name: fisiotheapp
description: Help pacients with fisiotherapy exercises

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Actor
      fonts:
        - asset: assets/fonts/Actor-Regular.ttf
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
        - asset: assets/fonts/ABeeZee-Italic.ttf
          style: italic
