name: fisiotheapp
description: Help pacients with fisiotherapy exercises

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SanFrancisco/pro/SF-Pro-Display-Black.otf
        - asset: assets/fonts/SanFrancisco/pro/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SanFrancisco/pro/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SanFrancisco/pro/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SanFrancisco/pro/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SanFrancisco/pro/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SanFrancisco/pro/SF-Pro-Display-Thin.otf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
