import 'package:pokedex/models/ability.dart';
import 'package:pokedex/models/evolution.dart';
import 'package:pokedex/models/location.dart';
import 'package:pokedex/models/pokemon.dart';

import '../models/pokemon_types.dart';

const pokemons = [
  Pokemon(
    pokedexNumber: 1,
    name: 'Bulbasaur',
    imageUrl:
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
    types: [PokemonTypes.grass, PokemonTypes.poison],
    description:
        'Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun\'s rays, the seed grows progressively larger.',
    species: 'Seed Pokémon',
    height: 0.7,
    weight: 6.9,
    abilities: [
      Ability(slot: 1, name: 'Overgrow', isHidden: false),
      Ability(slot: 3, name: 'Chlorophyll', isHidden: true),
    ],
    weaknesses: [
      PokemonTypes.fire,
      PokemonTypes.flying,
      PokemonTypes.ice,
      PokemonTypes.psychic,
    ],
    evYield: '1 Special Attack',
    catchRate: '45 (5.9% with PokéBall, full HP)',
    baseFriendship: 70,
    baseExp: 64,
    growthRate: 'Medium Slow',
    gender: '87.5%, 12.5%',
    eggGroups: 'Grass, Monster',
    eggCycles: '20 (4,884 - 5,140 steps)',
    locations: [
      Location(id: 1, name: '(Red/Blue/Yellow)'),
      Location(id: 226, name: '(Gold/Silver/Crystal)'),
      Location(id: 1, name: '(FireRed/LeafGreen)'),
      Location(id: 231, name: '(HeartGold/SoulSilver)'),
      Location(id: 080, name: '(X/Y - Central Kalos)'),
      Location(id: 1, name: '(Let\'s Go Pikachu/Let\'s Go Eevee)'),
    ],
    hp: 45,
    minHp: 200,
    maxHp: 294,
    attack: 49,
    minAttack: 92,
    maxAttack: 216,
    defense: 49,
    minDefense: 92,
    maxDefense: 216,
    specialAttack: 65,
    minSpecialAttack: 121,
    maxSpecialAttack: 251,
    specialDefense: 65,
    minSpecialDefense: 121,
    maxSpecialDefense: 251,
    speed: 45,
    minSpeed: 85,
    maxSpeed: 207,
    evolutions: [
      Evolution(basePokemonId: 1, level: 16, nextPokemonId: 2),
      Evolution(basePokemonId: 2, level: 32, nextPokemonId: 3),
    ],
  ),
  Pokemon(
    pokedexNumber: 4,
    name: 'Charmander',
    imageUrl:
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
    types: [PokemonTypes.fire],
    description:
        'The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.',
    species: 'Lizard Pokémon',
    height: 0.6,
    weight: 8.5,
    abilities: [
      Ability(slot: 1, name: 'Blaze', isHidden: false),
      Ability(slot: 3, name: 'Solar Power', isHidden: true),
    ],
    weaknesses: [
      PokemonTypes.ground,
      PokemonTypes.rock,
      PokemonTypes.water,
    ],
    evYield: '1 Speed',
    catchRate: '45 (5.9% with PokéBall, full HP)',
    baseFriendship: 70,
    baseExp: 62,
    growthRate: 'Medium Slow',
    gender: '87.5%, 12.5%',
    eggGroups: 'Dragon, Monster',
    eggCycles: '20 (4,884 - 5,140 steps)',
    locations: [
      Location(id: 4, name: '(Red/Blue/Yellow)'),
      Location(id: 229, name: '(Gold/Silver/Crystal)'),
      Location(id: 4, name: '(FireRed/LeafGreen)'),
      Location(id: 234, name: '(HeartGold/SoulSilver)'),
      Location(id: 083, name: '(X/Y - Central Kalos)'),
      Location(id: 4, name: '(Let\'s Go Pikachu/Let\'s Go Eevee)'),
      Location(id: 378, name: '(Sword/Shield)'),
    ],
    hp: 39,
    minHp: 188,
    maxHp: 282,
    attack: 52,
    minAttack: 98,
    maxAttack: 223,
    defense: 43,
    minDefense: 81,
    maxDefense: 203,
    specialAttack: 60,
    minSpecialAttack: 112,
    maxSpecialAttack: 240,
    specialDefense: 50,
    minSpecialDefense: 94,
    maxSpecialDefense: 218,
    speed: 65,
    minSpeed: 121,
    maxSpeed: 251,
    evolutions: [
      Evolution(basePokemonId: 4, level: 16, nextPokemonId: 5),
      Evolution(basePokemonId: 5, level: 36, nextPokemonId: 6),
    ],
  ),
  Pokemon(
    pokedexNumber: 7,
    name: 'Squirtle',
    imageUrl:
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
    types: [PokemonTypes.grass, PokemonTypes.poison],
    description:
        'Squirtle\'s shell is not merely used for protection. The shell\'s rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokémon to swim at high speeds.',
    species: 'Tiny Turtle Pokémon',
    height: 0.5,
    weight: 9.0,
    abilities: [
      Ability(slot: 1, name: 'Torrent', isHidden: false),
      Ability(slot: 3, name: 'Rain Dish', isHidden: true),
    ],
    weaknesses: [
      PokemonTypes.electric,
      PokemonTypes.grass,
    ],
    evYield: '1 Defense',
    catchRate: '45 (5.9% with PokéBall, full HP)',
    baseFriendship: 70,
    baseExp: 63,
    growthRate: 'Medium Slow',
    gender: '87.5%, 12.5%',
    eggGroups: 'Monster, Water 1',
    eggCycles: '20 (4,884 - 5,140 steps)',
    locations: [
      Location(id: 7, name: '(Red/Blue/Yellow)'),
      Location(id: 232, name: '(Gold/Silver/Crystal)'),
      Location(id: 7, name: '(FireRed/LeafGreen)'),
      Location(id: 237, name: '(HeartGold/SoulSilver)'),
      Location(id: 086, name: '(X/Y - Central Kalos)'),
      Location(id: 7, name: '(Let\'s Go Pikachu/Let\'s Go Eevee)'),
    ],
    hp: 44,
    minHp: 198,
    maxHp: 292,
    attack: 48,
    minAttack: 90,
    maxAttack: 214,
    defense: 65,
    minDefense: 121,
    maxDefense: 251,
    specialAttack: 50,
    minSpecialAttack: 94,
    maxSpecialAttack: 218,
    specialDefense: 64,
    minSpecialDefense: 119,
    maxSpecialDefense: 249,
    speed: 43,
    minSpeed: 81,
    maxSpeed: 203,
    evolutions: [
      Evolution(basePokemonId: 7, level: 16, nextPokemonId: 8),
      Evolution(basePokemonId: 8, level: 32, nextPokemonId: 9),
    ],
  ),
];
